version: '3.8'

services:
  # Front-end services
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - uni-hub-network

  # Backend Services
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=uni_hub_core.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/uni_hub
    depends_on:
      - db
    networks:
      - uni-hub-network

  # Database Services
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=uni_hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - uni-hub-network

  # Redis server (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - uni-hub-network

volumes:
  postgres_data:

networks:
  uni-hub-network:
    driver: bridge 